import { BaseEntity } from './base-entity';

export interface Role extends BaseEntity {
    name: RoleName;
    description: string;
}
export enum RoleName {
    ROLE_LIST_ALL_STAFFS='ROLE_LIST_ALL_STAFFS',
    ROLE_REGISTER_NEW_STAFF='ROLE_REGISTER_NEW_STAFF',
    ROLE_VIEW_STAFF_DETAILS='ROLE_VIEW_STAFF_DETAILS',
    ROLE_UPDATE_STAFF_DATA='ROLE_UPDATE_STAFF_DATA',
    ROLE_DELETE_STAFF='ROLE_DELETE_STAFF',
    ROLE_LIST_ALL_EMPLOYEES='ROLE_LIST_ALL_EMPLOYEES',
    ROLE_REGISTER_NEW_EMPLOYEE='ROLE_REGISTER_NEW_EMPLOYEE',
    ROLE_VIEW_EMPLOYEE_DETAILS='ROLE_VIEW_EMPLOYEE_DETAILS',
    ROLE_UPDATE_EMPLOYEE_DATA='ROLE_UPDATE_EMPLOYEE_DATA',
    ROLE_DELETE_EMPLOYEE='ROLE_DELETE_EMPLOYEE',
    ROLE_LIST_ALL_VACATIONS='ROLE_LIST_ALL_VACATIONS',
    ROLE_REGISTER_NEW_VACATION='ROLE_REGISTER_NEW_VACATION',
    ROLE_VIEW_VACATION_DETAILS='ROLE_VIEW_VACATION_DETAILS',
    ROLE_UPDATE_VACATION_DATA='ROLE_UPDATE_VACATION_DATA',
    ROLE_DELETE_VACATION='ROLE_DELETE_VACATION'
}